# Generated by Django 4.1.1 on 2023-02-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='img',
        ),
        migrations.AddField(
            model_name='products',
            name='img',
            field=models.ManyToManyField(to='catalog.productsimg'),
        ),
    ]
