# Generated by Django 4.1.1 on 2023-02-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
