# Generated by Django 4.1.6 on 2023-03-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Кількість товару в кошику')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='count_basket',
            field=models.ManyToManyField(to='users_page.count', verbose_name='Кількість товару в кошиках'),
        ),
    ]
