# Generated by Django 4.1.1 on 2023-02-05 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('users_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comparison',
            field=models.ManyToManyField(blank=True, null=True, related_name='comparison', to='catalog.products'),
        ),
        migrations.AddField(
            model_name='user',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='like', to='catalog.products'),
        ),
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basket', models.ManyToManyField(blank=True, null=True, to='catalog.products')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_page.basket'),
        ),
    ]
