# Generated by Django 4.1.1 on 2023-02-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('users_page', '0002_user_comparison_user_like_basket_user_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='basket',
            field=models.ManyToManyField(to='catalog.products'),
        ),
    ]
