# Generated by Django 4.1.6 on 2023-02-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('users_page', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='basket',
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.AddField(
            model_name='user',
            name='basket',
            field=models.ManyToManyField(related_name='bin', to='catalog.products', verbose_name='Кошик'),
        ),
    ]
