# Generated by Django 4.1.1 on 2023-02-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_products_img_products_img'),
        ('users_page', '0003_alter_basket_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='comparison',
            field=models.ManyToManyField(null=True, related_name='comparison', to='catalog.products'),
        ),
        migrations.AlterField(
            model_name='user',
            name='like',
            field=models.ManyToManyField(null=True, related_name='like', to='catalog.products'),
        ),
    ]
